/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_seeyou_generateJPG */

#ifndef _Included_com_find_guide_utils_CropAndScale
#define _Included_com_find_guide_utils_CropAndScale

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_find_guide_utils_CropAndScale
 * Method:    createGlobalFlags
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_find_guide_utils_CropAndScale_createGlobalFlags
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_find_guide_utils_CropAndScale
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_find_guide_utils_CropAndScale_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_find_guide_utils_CropAndScale
 * Method:    nativeCropJpg
 * Signature: (JLjava/lang/String;Ljava/lang/String;IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_find_guide_utils_CropAndScale_nativeCropJpg
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jint, jint, jint, jint,jint);

#ifdef __cplusplus
}
#endif
#endif
